name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        include:
          - php: '8.0'
            symfony: '6.0.*'
          - php: '8.1'
            symfony: '6.0.*'
          - php: '8.1'
            symfony: '6.1.*'
          - php: '8.2'
            symfony: '6.2.*'
          - php: '8.2'
            symfony: '6.3.*'
          - php: '8.2'
            symfony: '6.4.*'
          - php: '8.3'
            symfony: '6.4.*'
          - php: '8.2'
            symfony: '7.0.*'
          - php: '8.3'
            symfony: '7.0.*'
          - php: '8.2'
            symfony: '7.1.*'
          - php: '8.3'
            symfony: '7.1.*'
          - php: '8.4'
            symfony: '7.1.*'

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v2

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer run-script test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./build/logs/clover.xml
          verbose: true
